variables:
  DOCKER_TLS_CERTDIR: "/certs"
  APP: "my-app"
  TRIVY_CACHE_DIR: ".trivycache"

stages:
  - build
  - test

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" "$HARBOR_HOST" --password-stdin
  script:
    - docker build -t $APP .
    - docker tag $APP $HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_COMMIT_SHORT_SHA
    - docker tag $APP $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_COMMIT_SHORT_SHA
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
  tags:
    - docker


stages:
  - build
  - test
  - deploy


# EXISITNG PARST OF YOUR DOCKERFILE

deploy:
  stage: deploy
  before_script:
    - docker info
    - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" "$HARBOR_HOST" --password-stdin
  script:
    - docker pull $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
    - docker rm -f $APP || true
    - docker run -d --name $APP -p 80:80 $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
  tags:
    - dev-env
  needs:
    - container_scanning
